// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @notice Minimal interface for the UltraHonk verifier generated by bb.
 */
interface IHonkVerifier {
    function verify(
        bytes calldata _proof,
        bytes32[] calldata _publicInputs
    ) external view returns (bool);
}

/**
 * @title  IdentityRegistry
 * @notice Core identity management contract for Civyx.
 *
 *         Handles:
 *           - Identity registration with economic stake
 *           - ZK-proof-gated wallet linking
 *           - Nullifier tracking to prevent proof replay
 *           - Identity deactivation with stake withdrawal
 *           - Identity reactivation (preserves commitment + reputation)
 *
 * @dev    Uses OpenZeppelin AccessControl, Pausable, ReentrancyGuard.
 *
 *         Stake design:
 *           - minimumStake is the protocol floor — must stake at least this to exist
 *           - Organizers set their own per-context requirements (via OrganizerRegistry)
 *           - Stake is returned on deactivation — not permanently locked
 *           - On reactivation, user must re-stake >= minimumStake
 *           - Commitment and reputation are preserved across deactivate/reactivate cycles
 *
 *         Public inputs layout for wallet_link circuit (3 total):
 *           [0]     commitment      (Field)
 *           [1]     nullifier       (Field)
 *           [2]     wallet_address  (Field)
 */
contract IdentityRegistry is AccessControl, Pausable, ReentrancyGuard {

    // -------------------------------------------------------------------------
    // Roles
    // -------------------------------------------------------------------------

    bytes32 public constant PAUSER_ROLE   = keccak256("PAUSER_ROLE");
    bytes32 public constant OPERATOR_ROLE = keccak256("OPERATOR_ROLE");

    // -------------------------------------------------------------------------
    // Data Structures
    // -------------------------------------------------------------------------

    struct Identity {
        bytes32 commitment;   // pedersen_hash([secret]) — public anchor
        uint256 stake;        // native token currently locked
        uint256 createdBlock; // block number of first registration
        uint256 walletCount;  // number of currently linked wallets
        bool    active;       // false if deactivated
    }

    // -------------------------------------------------------------------------
    // State
    // -------------------------------------------------------------------------

    /// @notice Protocol floor — minimum stake to register or reactivate
    uint256 public minimumStake;

    /// @notice The UltraHonk ZK verifier (generated from wallet_link circuit)
    IHonkVerifier public walletLinkVerifier;

    /// @notice commitment => Identity record
    mapping(bytes32 => Identity) public identities;

    /// @notice wallet address => commitment it belongs to
    mapping(address => bytes32) public walletToCommitment;

    /// @notice nullifier => used flag (prevents proof replay)
    mapping(bytes32 => bool) public usedNullifiers;

    /// @notice commitment => array of linked wallet addresses
    mapping(bytes32 => address[]) private _linkedWallets;

    // -------------------------------------------------------------------------
    // Events
    // -------------------------------------------------------------------------

    event IdentityRegistered(bytes32 indexed commitment, address indexed registrant, uint256 stake);
    event IdentityDeactivated(bytes32 indexed commitment, address indexed caller, uint256 stakeReturned);
    event IdentityReactivated(bytes32 indexed commitment, address indexed caller, uint256 stake);
    event WalletLinked(bytes32 indexed commitment, address indexed wallet);
    event WalletUnlinked(bytes32 indexed commitment, address indexed wallet);
    event MinimumStakeUpdated(uint256 oldStake, uint256 newStake);
    event VerifierUpdated(address oldVerifier, address newVerifier);
    event StakeAdded(bytes32 indexed commitment, address indexed caller, uint256 added, uint256 total);
    event StakeWithdrawn(bytes32 indexed commitment, address indexed caller, uint256 withdrawn, uint256 remaining);

    // -------------------------------------------------------------------------
    // Errors
    // -------------------------------------------------------------------------

    error CommitmentAlreadyRegistered(bytes32 commitment);
    error InsufficientStake(uint256 provided, uint256 required);
    error WalletAlreadyLinked(address wallet);
    error WalletNotLinked(address wallet);
    error NullifierAlreadyUsed(bytes32 nullifier);
    error InvalidProof();
    error IdentityNotActive(bytes32 commitment);
    error IdentityAlreadyActive(bytes32 commitment);
    error IdentityDoesNotExist(bytes32 commitment);
    error NotIdentityOwner();
    error CannotUnlinkLastWallet();
    error ZeroCommitment();
    error ZeroAddress();
    error StakeTransferFailed();
    error WithdrawExceedsStake(uint256 requested, uint256 available);
    error StakeBelowMinimum(uint256 remaining, uint256 minimum);

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    constructor(
        uint256 _minimumStake,
        address _walletLinkVerifier,
        address _admin
    ) {
        if (_walletLinkVerifier == address(0)) revert ZeroAddress();
        if (_admin == address(0))              revert ZeroAddress();

        minimumStake       = _minimumStake;
        walletLinkVerifier = IHonkVerifier(_walletLinkVerifier);

        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(PAUSER_ROLE,        _admin);
        _grantRole(OPERATOR_ROLE,      _admin);
    }

    // -------------------------------------------------------------------------
    // Identity Registration
    // -------------------------------------------------------------------------

    /**
     * @notice Register a new identity commitment on-chain.
     * @dev    The caller's wallet is automatically linked as the first wallet.
     *         If the commitment was previously deactivated, this reverts —
     *         use reactivateIdentity() instead.
     * @param commitment  pedersen_hash([secret]), computed locally by the user
     */
    function registerIdentity(bytes32 commitment)
        external
        payable
        nonReentrant
        whenNotPaused
    {
        if (commitment == bytes32(0))
            revert ZeroCommitment();
        if (identities[commitment].createdBlock != 0)
            revert CommitmentAlreadyRegistered(commitment);
        if (walletToCommitment[msg.sender] != bytes32(0))
            revert WalletAlreadyLinked(msg.sender);
        if (msg.value < minimumStake)
            revert InsufficientStake(msg.value, minimumStake);

        identities[commitment] = Identity({
            commitment:   commitment,
            stake:        msg.value,
            createdBlock: block.number,
            walletCount:  1,
            active:       true
        });

        walletToCommitment[msg.sender] = commitment;
        _linkedWallets[commitment].push(msg.sender);

        emit IdentityRegistered(commitment, msg.sender, msg.value);
        emit WalletLinked(commitment, msg.sender);
    }

    // -------------------------------------------------------------------------
    // Deactivation & Reactivation
    // -------------------------------------------------------------------------

    /**
     * @notice Deactivate your identity and withdraw your stake.
     *
     * @dev    Calling wallet must be linked to the identity.
     *         Sets active = false and transfers stake back to caller.
     *         Commitment and reputation in ReputationRegistry are preserved.
     *         Linked wallets remain in storage (not wiped).
     *         Identity can be reactivated later via reactivateIdentity().
     */
    function deactivateIdentity() external nonReentrant whenNotPaused {
        bytes32 commitment = walletToCommitment[msg.sender];
        if (commitment == bytes32(0)) revert WalletNotLinked(msg.sender);

        Identity storage id = identities[commitment];
        if (!id.active) revert IdentityNotActive(commitment);

        uint256 stakeToReturn = id.stake;
        id.active = false;
        id.stake  = 0;

        emit IdentityDeactivated(commitment, msg.sender, stakeToReturn);

        // Transfer stake back — after state changes (checks-effects-interactions)
        (bool ok, ) = msg.sender.call{value: stakeToReturn}("");
        if (!ok) revert StakeTransferFailed();
    }

    /**
     * @notice Reactivate a previously deactivated identity.
     *
     * @dev    Calling wallet must still be linked to the identity.
     *         Requires re-staking >= minimumStake.
     *         Commitment and all reputation accumulated before deactivation
     *         are preserved — nothing is wiped.
     */
    function reactivateIdentity()
        external
        payable
        nonReentrant
        whenNotPaused
    {
        bytes32 commitment = walletToCommitment[msg.sender];
        if (commitment == bytes32(0)) revert WalletNotLinked(msg.sender);

        Identity storage id = identities[commitment];
        if (id.active) revert IdentityAlreadyActive(commitment);
        if (msg.value < minimumStake)
            revert InsufficientStake(msg.value, minimumStake);

        id.active = true;
        id.stake  = msg.value;

        emit IdentityReactivated(commitment, msg.sender, msg.value);
    }

    // -------------------------------------------------------------------------
    // Stake Management
    // -------------------------------------------------------------------------

    /**
     * @notice Add more stake to your active identity.
     * @dev    Any linked wallet can top up the stake.
     *         Stake is tracked per identity commitment, not per wallet.
     *         There is no upper bound — stake any amount above zero.
     */
    function addStake() external payable nonReentrant whenNotPaused {
        bytes32 commitment = walletToCommitment[msg.sender];
        if (commitment == bytes32(0)) revert WalletNotLinked(msg.sender);

        Identity storage id = identities[commitment];
        if (!id.active) revert IdentityNotActive(commitment);
        if (msg.value == 0) revert InsufficientStake(0, 1);

        id.stake += msg.value;
        emit StakeAdded(commitment, msg.sender, msg.value, id.stake);
    }

    /**
     * @notice Withdraw a portion of your stake.
     * @dev    At least minimumStake must remain locked at all times.
     *         Any linked wallet can trigger a partial withdrawal.
     *         Funds are sent to msg.sender (the calling wallet).
     * @param  amount  Amount of native token to withdraw, in wei.
     */
    function withdrawStake(uint256 amount) external nonReentrant whenNotPaused {
        bytes32 commitment = walletToCommitment[msg.sender];
        if (commitment == bytes32(0)) revert WalletNotLinked(msg.sender);

        Identity storage id = identities[commitment];
        if (!id.active) revert IdentityNotActive(commitment);
        if (amount > id.stake) revert WithdrawExceedsStake(amount, id.stake);

        uint256 remaining = id.stake - amount;
        if (remaining < minimumStake) revert StakeBelowMinimum(remaining, minimumStake);

        id.stake -= amount;
        emit StakeWithdrawn(commitment, msg.sender, amount, id.stake);

        // Transfer after state update (checks-effects-interactions)
        (bool ok, ) = msg.sender.call{value: amount}("");
        if (!ok) revert StakeTransferFailed();
    }

    // -------------------------------------------------------------------------
    // Wallet Linking
    // -------------------------------------------------------------------------

    /**
     * @notice Link an additional wallet to an existing identity using a ZK proof.
     *
     * @dev    The proof is generated client-side by the wallet_link Noir circuit.
     *         It proves: pedersen_hash([secret]) == commitment
     *                AND pedersen_hash([secret, wallet]) == nullifier
     *         without revealing secret.
     *
     *         Public inputs array (bytes32[3]):
     *           [0]     commitment
     *           [1]     nullifier
     *           [2]     bytes32(uint256(uint160(msg.sender)))
     *
     * @param commitment  The identity commitment to link to
     * @param proof       UltraHonk proof bytes from bb prove
     * @param nullifier   pedersen_hash([secret, wallet]) — one-time use
     */
    function linkWallet(
        bytes32 commitment,
        bytes calldata proof,
        bytes32 nullifier
    )
        external
        nonReentrant
        whenNotPaused
    {
        if (!identities[commitment].active)
            revert IdentityNotActive(commitment);
        if (walletToCommitment[msg.sender] != bytes32(0))
            revert WalletAlreadyLinked(msg.sender);
        if (usedNullifiers[nullifier])
            revert NullifierAlreadyUsed(nullifier);

        bytes32[] memory publicInputs = new bytes32[](3);
        publicInputs[0] = commitment;
        publicInputs[1] = nullifier;
        publicInputs[2] = bytes32(uint256(uint160(msg.sender)));

        if (!walletLinkVerifier.verify(proof, publicInputs))
            revert InvalidProof();

        usedNullifiers[nullifier]      = true;
        walletToCommitment[msg.sender] = commitment;
        identities[commitment].walletCount++;
        _linkedWallets[commitment].push(msg.sender);

        emit WalletLinked(commitment, msg.sender);
    }

    /**
     * @notice Unlink the calling wallet from its identity.
     * @dev    Cannot unlink the last wallet — would orphan the identity.
     *         Use deactivateIdentity() to fully exit.
     */
    function unlinkWallet() external nonReentrant whenNotPaused {
        bytes32 commitment = walletToCommitment[msg.sender];
        if (commitment == bytes32(0)) revert WalletNotLinked(msg.sender);

        Identity storage id = identities[commitment];
        if (id.walletCount <= 1) revert CannotUnlinkLastWallet();

        walletToCommitment[msg.sender] = bytes32(0);
        id.walletCount--;

        address[] storage wallets = _linkedWallets[commitment];
        uint256 len = wallets.length;
        for (uint256 i = 0; i < len; i++) {
            if (wallets[i] == msg.sender) {
                wallets[i] = wallets[len - 1];
                wallets.pop();
                break;
            }
        }

        emit WalletUnlinked(commitment, msg.sender);
    }

    // -------------------------------------------------------------------------
    // View Functions
    // -------------------------------------------------------------------------

    /// @notice Returns true if wallet belongs to a registered, active identity
    function verifyIdentity(address wallet) external view returns (bool) {
        bytes32 commitment = walletToCommitment[wallet];
        if (commitment == bytes32(0)) return false;
        return identities[commitment].active;
    }

    /// @notice Returns the commitment associated with a wallet (0 if none)
    function getCommitment(address wallet) external view returns (bytes32) {
        return walletToCommitment[wallet];
    }

    /// @notice Returns the stake locked by the identity associated with a wallet
    function getIdentityStake(address wallet) external view returns (uint256) {
        bytes32 commitment = walletToCommitment[wallet];
        if (commitment == bytes32(0)) return 0;
        return identities[commitment].stake;
    }

    /// @notice Returns the number of wallets linked to the same identity as wallet
    function getLinkedWalletCount(address wallet) external view returns (uint256) {
        bytes32 commitment = walletToCommitment[wallet];
        if (commitment == bytes32(0)) return 0;
        return identities[commitment].walletCount;
    }

    /// @notice Returns all wallet addresses linked to a commitment
    function getLinkedWallets(bytes32 commitment) external view returns (address[] memory) {
        return _linkedWallets[commitment];
    }

    /// @notice Returns the full Identity struct for a commitment
    function getIdentity(bytes32 commitment) external view returns (Identity memory) {
        return identities[commitment];
    }

    // -------------------------------------------------------------------------
    // Admin
    // -------------------------------------------------------------------------

    function setMinimumStake(uint256 newStake) external onlyRole(DEFAULT_ADMIN_ROLE) {
        emit MinimumStakeUpdated(minimumStake, newStake);
        minimumStake = newStake;
    }

    function setVerifier(address newVerifier) external onlyRole(DEFAULT_ADMIN_ROLE) {
        if (newVerifier == address(0)) revert ZeroAddress();
        emit VerifierUpdated(address(walletLinkVerifier), newVerifier);
        walletLinkVerifier = IHonkVerifier(newVerifier);
    }

    function pause()   external onlyRole(PAUSER_ROLE) { _pause(); }
    function unpause() external onlyRole(PAUSER_ROLE) { _unpause(); }

    receive() external payable {}
}
